version: "3"
services:
  prometheus:
    image: quay.io/prometheus/prometheus:latest
    # ports:
    #  - 9090:9090
    volumes:
     - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
     - "./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml"
    env_file:
        prometheus-stack.env
    command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--web.enable-lifecycle'
        - "--web.external-url=http://localhost:1201/prometheus"
        - "--web.route-prefix=/"
    depends_on:
        - alertmanager

  alertmanager:
    image: quay.io/prometheus/alertmanager:latest
    environment:
        no_proxy: "gateway"
    # Uncomment the following port mapping if you wish to expose the Prometheus
    #  Alertmanager UI.
    # ports:
    #     - 9093:9093
    volumes:
     - "./alertmanager/alertmanager.yml:/alertmanager.yml"
    env_file:
        prometheus-stack.env
    command:
        - '--config.file=/alertmanager.yml'
        - '--storage.path=/alertmanager'

  grafana:
    image: grafana/grafana:latest
    # ports:
    #     - "3000:3000"
    volumes:
        - "./grafana/storage:/var/lib/grafana"
        - "./grafana/conf/grafana.ini:/etc/grafana/grafana.ini"
    env_file:
        prometheus-stack.env

  nginx:
    image: nginx:alpine
    ports:
     - 1201:1201
    volumes:
        - "./nginx/default.template:/etc/nginx/conf.d/default.template"
    env_file:
        prometheus-stack.env
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
        - prometheus
        - alertmanager
        - grafana